[project]
name = "fastapi-practice"
version = "0.1.0"
description = ""
authors = [
    {name = "Habib-ur-Rehman",email = "habibhr112211@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.52.1,<0.53.0)",
    "sqlmodel (>=0.0.39,<0.0.40)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)"
]

[tool.poetry]
packages = [{include = "fastapi_practice", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "httpx (>=0.28.1,<0.29.0)"
]
